---
title: "Análise espacial da mortalidade infantil em Sergipe, 2010"
description: |
 Objetivo: demonstrar os passos necessários para analisar espacialmente dados de mortalidade infantil 
author:
  - name: Daniel Marques
    url: {}
date: 2022-02-02
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{css, echo=FALSE}
p {
  font-size: 12px;
}
```

<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/css/style.css" />
  </head>
   <body>
    <h3>Carregamento de pacotes</h3>
    <p>
    Use o seguinte comando:</br>
    library(pacman)</br>
    p_load(rio, here, viridis, tidyverse, viridis,
       ggspatial, sf, rayshader)
       
    </p>
```{r}
library(pacman)
p_load(rio, here, viridis, tidyverse, viridis,
       ggspatial, sf)
library(rayshader)
```
    <h3>Execução</h3>
```{r}
dados_ipea <- import(here("analise_espacial", "SE_IPEA.xlsx"), 
                        which = "IDH_2010")

dados_ipea <- janitor::clean_names(dados_ipea)

dados_mort_inf <- dados_ipea %>% dplyr::select(codigo_do_municipio, municipio, mortalidade_infantil)
  
sf_sergipe <- st_read("C:/DataScienceUSP/Analise_espacial/Projeto/SE_Municipios_2020.shp")
sf_sergipe$CD_MUN <- substring(sf_sergipe$CD_MUN, 1, 6)

dados_ipea <- dados_ipea %>%
  rename(CD_MUN = codigo_do_municipio)

dados_ipea$CD_MUN <- as.character(dados_ipea$CD_MUN)

sf_sergipe_ipea <-left_join(sf_sergipe, dados_ipea, 
                            by = "CD_MUN")

ggMortInf <- ggplot(data = sf_sergipe_ipea) + 
  geom_sf(aes(fill = mortalidade_infantil)) + 
  scale_fill_viridis("Mortalidade Infantil") +
  ggtitle("Taxa de Mortalidade Infantil em Sergipe, 2010") +
  theme_bw() +
  annotation_north_arrow(width = unit(0.75, "cm"),
                         height = unit(1.0, "cm"))
  
```
```{r echo=FALSE}
ggMortInf
```


  </body>
</html>


```{r}

```


Learn more about using Distill at <https://rstudio.github.io/distill>.


